// Administrative locations of Bangladesh (divisions → districts → upazilas).
// Used for route source/destination/route-stop suggestions across the project.

export const BANGLADESH_DIVISIONS = [
  "Dhaka",
  "Chattogram",
  "Barishal",
  "Khulna",
  "Rajshahi",
  "Rangpur",
  "Mymensingh",
  "Sylhet",
] as const;

export const DIVISION_DISTRICTS: Record<string, string[]> = {
  Dhaka: [
    "Dhaka",
    "Faridpur",
    "Gazipur",
    "Gopalganj",
    "Kishoreganj",
    "Madaripur",
    "Manikganj",
    "Munshiganj",
    "Narayanganj",
    "Narsingdi",
    "Rajbari",
    "Shariatpur",
    "Tangail",
  ],
  Chattogram: [
    "Chattogram",
    "Cox's Bazar",
    "Bandarban",
    "Khagrachhari",
    "Rangamati",
    "Noakhali",
    "Feni",
    "Lakshmipur",
    "Cumilla",
    "Brahmanbaria",
    "Chandpur",
  ],
  Barishal: [
    "Barishal",
    "Barguna",
    "Bhola",
    "Jhalokati",
    "Patuakhali",
    "Pirojpur",
  ],
  Khulna: [
    "Khulna",
    "Bagerhat",
    "Satkhira",
    "Jessore",
    "Magura",
    "Narail",
    "Jhenaidah",
    "Kushtia",
    "Chuadanga",
    "Meherpur",
  ],
  Rajshahi: [
    "Rajshahi",
    "Natore",
    "Naogaon",
    "Chapainawabganj",
    "Pabna",
    "Sirajganj",
    "Bogura",
    "Joypurhat",
  ],
  Rangpur: [
    "Rangpur",
    "Dinajpur",
    "Kurigram",
    "Gaibandha",
    "Lalmonirhat",
    "Nilphamari",
    "Panchagarh",
    "Thakurgaon",
  ],
  Mymensingh: ["Mymensingh", "Jamalpur", "Netrokona", "Sherpur"],
  Sylhet: ["Sylhet", "Moulvibazar", "Habiganj", "Sunamganj"],
};

export const DISTRICT_UPAZILAS: Record<string, string[]> = {
  // ---------------- Dhaka ----------------
  Dhaka: [
    "Dhamrai",
    "Dohar",
    "Keraniganj",
    "Nawabganj",
    "Savar",
    "Tejgaon Circle",
  ],
  Faridpur: [
    "Alfadanga",
    "Bhanga",
    "Boalmari",
    "Charbhadrasan",
    "Faridpur Sadar",
    "Madhukhali",
    "Nagarkanda",
    "Sadarpur",
    "Saltha",
  ],
  Gazipur: ["Gazipur Sadar", "Kaliakair", "Kaliganj", "Kapasia", "Sreepur"],
  Gopalganj: [
    "Gopalganj Sadar",
    "Kashiani",
    "Kotalipara",
    "Muksudpur",
    "Tungipara",
  ],
  Kishoreganj: [
    "Astagram",
    "Bajitpur",
    "Bhairab",
    "Hossainpur",
    "Itna",
    "Karimganj",
    "Katiadi",
    "Kishoreganj Sadar",
    "Kuliarchar",
    "Mithamain",
    "Nikli",
    "Pakundia",
    "Tarail",
  ],
  Madaripur: ["Rajoir", "Madaripur Sadar", "Kalkini", "Shibchar"],
  Manikganj: [
    "Daulatpur",
    "Gheor",
    "Harirampur",
    "Kaliahair",
    "Manikganj Sadar",
    "Saturia",
    "Shibalaya",
    "Singair",
  ],
  Munshiganj: [
    "Gazaria",
    "Lohajang",
    "Munshiganj Sadar",
    "Sirajdikhan",
    "Sreenagar",
    "Tongibari",
  ],
  Narayanganj: [
    "Araihazar",
    "Bandar",
    "Narayanganj Sadar",
    "Rupganj",
    "Sonargaon",
  ],
  Narsingdi: [
    "Narsingdi Sadar",
    "Belabo",
    "Monohardi",
    "Palash",
    "Raipura",
    "Shibpur",
  ],
  Rajbari: [
    "Baliakandi",
    "Goalandaghat",
    "Pangsha",
    "Rajbari Sadar",
    "Kalukhali",
  ],
  Shariatpur: [
    "Shariatpur Sadar",
    "Damudya",
    "Gosairhat",
    "Naria",
    "Bhedarganj",
    "Zajira",
  ],
  Tangail: [
    "Gopalpur",
    "Basail",
    "Bhuapur",
    "Delduar",
    "Ghatail",
    "Kalihati",
    "Madhupur",
    "Mirzapur",
    "Nagarpur",
    "Sakhipur",
    "Tangail Sadar",
    "Dhanbari",
  ],
  // ---------------- Chattogram ----------------
  Chattogram: [
    "Anwara",
    "Banshkhali",
    "Boalkhali",
    "Chandananish",
    "Fatikchhari",
    "Hathazari",
    "Lohagara",
    "Mirsharai",
    "Patiya",
    "Rangunia",
    "Raozan",
    "Sandwip",
    "Satkania",
    "Sitakunda",
    "Karnafuli",
  ],
  "Cox's Bazar": [
    "Cox's Bazar Sadar",
    "Chakaria",
    "Kutubdia",
    "Maheshkhali",
    "Ramu",
    "Teknaf",
    "Ukhia",
    "Pekua",
  ],
  Bandarban: [
    "Bandarban Sadar",
    "Thanchi",
    "Lama",
    "Naikhongchhari",
    "Ali Kadam",
    "Rowangchhari",
    "Ruma",
  ],
  Khagrachhari: [
    "Dighinala",
    "Khagrachhari Sadar",
    "Lakshmichhari",
    "Mahalchhari",
    "Manikchhari",
    "Matiranga",
    "Panchhari",
    "Ramgarh",
    "Guimara",
  ],
  Rangamati: [
    "Rangamati Sadar",
    "Belaichhari",
    "Bagaichhari",
    "Barkal",
    "Juraichhari",
    "Langadu",
    "Naniyachar",
    "Rajasthali",
    "Kaptai",
    "Kawkhali",
  ],
  Noakhali: [
    "Noakhali Sadar",
    "Begumganj",
    "Chatkhil",
    "Companyganj",
    "Hatiya",
    "Senbagh",
    "Sonaimuri",
    "Subarnachar",
    "Kabirhat",
  ],
  Feni: [
    "Feni Sadar",
    "Chagalnaiya",
    "Daganbhuiyan",
    "Parshuram",
    "Sonagazi",
    "Fulgazi",
  ],
  Lakshmipur: [
    "Lakshmipur Sadar",
    "Raipur",
    "Ramganj",
    "Ramgati",
    "Kamalnagar",
  ],
  Cumilla: [
    "Barura",
    "Brahmanpara",
    "Burichang",
    "Chandina",
    "Chauddagram",
    "Daudkandi",
    "Debidwar",
    "Homna",
    "Laksam",
    "Muradnagar",
    "Nangalkot",
    "Cumilla Sadar",
    "Meghna",
    "Monohorganj",
    "Sadarsouth",
    "Titas",
  ],
  Brahmanbaria: [
    "Brahmanbaria Sadar",
    "Kasba",
    "Nasirnagar",
    "Sarail",
    "Ashuganj",
    "Akhaura",
    "Nabinagar",
    "Bancharampur",
    "Bijoynagar",
  ],
  Chandpur: [
    "Chandpur Sadar",
    "Hajiganj",
    "Kachua",
    "Faridganj",
    "Matlab North",
    "Matlab South",
    "Shahrasti",
    "Haimchar",
  ],
  // ---------------- Barishal ----------------
  Barishal: [
    "Agailjhara",
    "Babuganj",
    "Bakerganj",
    "Banaripara",
    "Gaurnadi",
    "Hizla",
    "Barishal Sadar",
    "Mehendiganj",
    "Muladi",
    "Wazirpur",
  ],
  Barguna: [
    "Amtali",
    "Barguna Sadar",
    "Betagi",
    "Bamna",
    "Patharghata",
    "Taltali",
  ],
  Bhola: [
    "Bhola Sadar",
    "Burhanuddin",
    "Char Fasson",
    "Daulatkhan",
    "Monpura",
    "Tazumuddin",
    "Lalmohan",
  ],
  Jhalokati: ["Jhalokati Sadar", "Kathalia", "Nalchity", "Rajapur"],
  Patuakhali: [
    "Bauphal",
    "Dashmina",
    "Galachipa",
    "Kalapara",
    "Patuakhali Sadar",
    "Mirzaganj",
    "Dumki",
    "Rangabali",
  ],
  Pirojpur: [
    "Bhandaria",
    "Kawkhali",
    "Mathbaria",
    "Nazirpur",
    "Pirojpur Sadar",
    "Nesarabad",
    "Zianagar",
  ],
  // ---------------- Khulna ----------------
  Khulna: [
    "Batiaghata",
    "Dacope",
    "Dumuria",
    "Dighalia",
    "Koyra",
    "Paikgachha",
    "Phultala",
    "Rupsha",
    "Terokhada",
  ],
  Bagerhat: [
    "Bagerhat Sadar",
    "Chitalmari",
    "Fakirhat",
    "Kachua",
    "Mollahat",
    "Mongla",
    "Morrelganj",
    "Rampal",
    "Sarankhola",
  ],
  Satkhira: [
    "Assasuni",
    "Debhata",
    "Kalaroa",
    "Kaliganj",
    "Satkhira Sadar",
    "Shyamnagar",
    "Tala",
  ],
  Jessore: [
    "Abhaynagar",
    "Bagherpara",
    "Chougachha",
    "Jhikargacha",
    "Keshabpur",
    "Jessore Sadar",
    "Manirampur",
    "Sharsha",
  ],
  Magura: ["Magura Sadar", "Mohammadpur", "Shalikha", "Sreepur"],
  Narail: ["Kalia", "Lohagara", "Narail Sadar"],
  Jhenaidah: [
    "Harinakunda",
    "Jhenaidah Sadar",
    "Kaliganj",
    "Kotchandpur",
    "Maheshpur",
    "Shailkupa",
  ],
  Kushtia: [
    "Bheramara",
    "Daulatpur",
    "Khoksa",
    "Kumarkhali",
    "Kushtia Sadar",
    "Mirpur",
  ],
  Chuadanga: ["Alamdanga", "Chuadanga Sadar", "Damurhuda", "Jibannagar"],
  Meherpur: ["Gangni", "Meherpur Sadar", "Mujibnagar"],
  // ---------------- Rajshahi ----------------
  Rajshahi: [
    "Bagha",
    "Bagmara",
    "Charghat",
    "Durgapur",
    "Godagari",
    "Mohanpur",
    "Paba",
    "Puthia",
    "Tanore",
  ],
  Natore: [
    "Natore Sadar",
    "Baraigram",
    "Bagatipara",
    "Lalpur",
    "Singra",
    "Gurudaspur",
    "Naldanga",
  ],
  Naogaon: [
    "Atrai",
    "Badalgachhi",
    "Dhamoirhat",
    "Manda",
    "Mahadevpur",
    "Naogaon Sadar",
    "Niamatpur",
    "Patnitala",
    "Porsha",
    "Raninagar",
    "Sapahar",
  ],
  Chapainawabganj: [
    "Bholahat",
    "Gomastapur",
    "Nachole",
    "Chapainawabganj Sadar",
    "Shibganj",
  ],
  Pabna: [
    "Atgharia",
    "Bera",
    "Bhangura",
    "Chatmohar",
    "Faridpur",
    "Ishwardi",
    "Pabna Sadar",
    "Santhia",
    "Sujanagar",
  ],
  Sirajganj: [
    "Belkuchi",
    "Chauhali",
    "Kamarkhanda",
    "Kazipur",
    "Raiganj",
    "Shahjadpur",
    "Sirajganj Sadar",
    "Tarash",
    "Ullahpara",
  ],
  Bogura: [
    "Adamdighi",
    "Bogura Sadar",
    "Dhunat",
    "Dhupchanchia",
    "Gabtali",
    "Kahaloo",
    "Nandigram",
    "Sariakandi",
    "Shajahanpur",
    "Sherpur",
    "Shibganj",
    "Sonatala",
  ],
  Joypurhat: ["Akkelpur", "Joypurhat Sadar", "Kalai", "Khetlal", "Panchbibi"],
  // ---------------- Rangpur ----------------
  Rangpur: [
    "Badarganj",
    "Mithapukur",
    "Gangachara",
    "Kaunia",
    "Rangpur Sadar",
    "Pirgachha",
    "Pirganj",
    "Taraganj",
  ],
  Dinajpur: [
    "Birampur",
    "Birganj",
    "Biral",
    "Bochaganj",
    "Chirirbandar",
    "Phulbari",
    "Ghoraghat",
    "Hakimpur",
    "Kaharole",
    "Khansama",
    "Dinajpur Sadar",
    "Nawabganj",
    "Parbatipur",
  ],
  Kurigram: [
    "Bhurungamari",
    "Chilmari",
    "Phulbari",
    "Kurigram Sadar",
    "Nageshwari",
    "Rajarhat",
    "Rajibpur",
    "Rhumari",
    "Ulipur",
  ],
  Gaibandha: [
    "Gaibandha Sadar",
    "Sadullapur",
    "Palashbari",
    "Gobindaganj",
    "Sundarganj",
    "Saghata",
    "Phulchhari",
  ],
  Lalmonirhat: [
    "Lalmonirhat Sadar",
    "Aditmari",
    "Kaliganj",
    "Hatibandha",
    "Patgram",
  ],
  Nilphamari: [
    "Nilphamari Sadar",
    "Saidpur",
    "Jaldhaka",
    "Kishoreganj",
    "Domar",
    "Dimla",
  ],
  Panchagarh: ["Panchagarh Sadar", "Boda", "Debiganj", "Atwari", "Tentulia"],
  Thakurgaon: [
    "Thakurgaon Sadar",
    "Baliadangi",
    "Haripur",
    "Ranisankail",
    "Pirganj",
  ],
  // ---------------- Mymensingh ----------------
  Mymensingh: [
    "Bhaluka",
    "Dhobaura",
    "Fulbaria",
    "Gaffargaon",
    "Gauripur",
    "Haluaghat",
    "Ishwarganj",
    "Mymensingh Sadar",
    "Muktagachha",
    "Nandail",
    "Phulpur",
    "Trishal",
  ],
  Jamalpur: [
    "Bakshiganj",
    "Dewanganj",
    "Isampur",
    "Jamalpur Sadar",
    "Sarishabari",
    "Melandaha",
  ],
  Netrokona: [
    "Atpara",
    "Barhatta",
    "Durgapur",
    "Khaliajuri",
    "Kalmakanda",
    "Kendra",
    "Madann",
    "Mohanganj",
    "Netrokona Sadar",
    "Purbadhala",
  ],
  Sherpur: ["Jhenaigati", "Nakla", "Nalitabari", "Sherpur Sadar", "Sreebardi"],
  // ---------------- Sylhet ----------------
  Sylhet: [
    "Balaganj",
    "Beanibazar",
    "Bishwanath",
    "Companiganj",
    "Fenchuganj",
    "Golapganj",
    "Gowainghat",
    "Jaintiapur",
    "Kanaighat",
    "Sylhet Sadar",
    "Zakiganj",
    "Dakshinsurma",
    "Osmaninagar",
  ],
  Moulvibazar: [
    "Barlekha",
    "Kamalganj",
    "Kulaura",
    "Moulvibazar Sadar",
    "Rajnagar",
    "Sreemangal",
    "Juri",
  ],
  Habiganj: [
    "Ajmiriganj",
    "Baniachong",
    "Bahubal",
    "Chunarughat",
    "Habiganj Sadar",
    "Lakhai",
    "Madhabpur",
    "Nabiganj",
    "Shayestaganj",
  ],
  Sunamganj: [
    "Bishwambharpur",
    "Chhatak",
    "Derai",
    "Dharampasha",
    "Dowarabazar",
    "Jagannathpur",
    "Jamalganj",
    "Sullah",
    "Sunamganj Sadar",
    "Tahirpur",
    "Shantiganj",
  ],
};

export const BANGLADESH_DISTRICTS: readonly string[] =
  BANGLADESH_DIVISIONS.flatMap((division) => DIVISION_DISTRICTS[division]);

export const UPAZILAS: readonly string[] = BANGLADESH_DISTRICTS.flatMap(
  (district) => DISTRICT_UPAZILAS[district],
);

// Well-known bus terminals and junctions used as route stops on major highways.
export const MAJOR_BUS_STOPS = [
  "Dhaka (Kalyanpur)",
  "Dhaka (Gabtoli)",
  "Dhaka (Sayedabad)",
  "Dhaka (Mohakhali)",
  "Dhaka (Abdullahpur)",
  "Chandra Junction",
  "Kanchpur Junction",
  "Tongi Bypass",
  "Joydebpur Bus Stand",
  "Nabinagar Bus Stand",
  "Kaliakoir",
  "Bhuapur",
  "Elenga Bus Stand",
  "Jamuna Bridge (East)",
  "Hatikumrul",
  "Bonpara Bypass",
  "Borogola (Bogura)",
  "Natore Bipin Bypass",
  "Rajshahi (Shiroil Terminal)",
  "Cumilla (Candina)",
  "Mainamati Bypass",
  "Daudkandi Bypass",
  "Postbari (Brahmanbaria)",
  "Bhairab Bypass",
  "Haripur (Shaistaganj)",
  "Sylhet (Khadimnagar)",
  "Feni (Muhuri Bypass)",
  "Chattogram (Dampara)",
  "Chattogram (Kadamtali)",
  "Battali (Chattogram)",
  "Cox's Bazar (Hotel Motel Zone)",
  "Khulna (Sonadanga)",
  "Kushtia (Khunka More)",
  "Jashore (Kotchadpur)",
  "Barishal (Rupatali)",
  "Patuakhali",
  "Mymensingh (Kewatkhali)",
  "Tangail (Puratan Bus Stand)",
  "Rangpur (Central Bus Terminal)",
  "Dinajpur (K.N. Bazar)",
  "Pabna (Chowmatha)",
  "Sirajganj (Kamarkhondo)",
  "Thakurgaon",
  "Sunamganj",
  "Habiganj",
  "Sreemangal",
  "Chandpur (College Road)",
  "Chowmuhani (Noakhali)",
  "Lakshmipur",
  "Bhanga (Faridpur)",
  "Gopalganj",
  "Jamalpur (Sherpur Road)",
] as const;

export type LocationLevel = "Terminal" | "Upazila" | "District" | "Division";

const TERMINAL_SET = new Set<string>(MAJOR_BUS_STOPS);
const UPAZILA_SET = new Set<string>(UPAZILAS);
const DISTRICT_SET = new Set<string>(BANGLADESH_DISTRICTS);
const DIVISION_SET = new Set<string>(BANGLADESH_DIVISIONS);

export const locationLevel = (name: string): LocationLevel | null => {
  if (TERMINAL_SET.has(name)) return "Terminal";
  if (UPAZILA_SET.has(name)) return "Upazila";
  if (DISTRICT_SET.has(name)) return "District";
  if (DIVISION_SET.has(name)) return "Division";
  return null;
};

export const getDistrictsForDivision = (division: string): string[] =>
  DIVISION_DISTRICTS[division] ?? [];

export const getUpazilasForDistrict = (district: string): string[] =>
  DISTRICT_UPAZILAS[district] ?? [];

export const getDivisionForDistrict = (district: string): string | null => {
  for (const division of BANGLADESH_DIVISIONS) {
    if (DIVISION_DISTRICTS[division].includes(district)) return division;
  }
  return null;
};

export const getDistrictForUpazila = (upazila: string): string | null => {
  for (const district of BANGLADESH_DISTRICTS) {
    if (DISTRICT_UPAZILAS[district].includes(upazila)) return district;
  }
  return null;
};

// Full suggestion pool ordered: terminals first, then upazilas, districts, divisions.
export const LOCATION_SUGGESTIONS: string[] = [
  ...MAJOR_BUS_STOPS,
  ...UPAZILAS,
  ...BANGLADESH_DISTRICTS,
  ...BANGLADESH_DIVISIONS,
].filter((loc, index, arr) => arr.indexOf(loc) === index);

export const filterLocations = (
  query: string,
  limit = 10,
): Array<{ value: string; level: LocationLevel }> => {
  const q = query.trim().toLowerCase();
  const pool = q
    ? LOCATION_SUGGESTIONS.filter((loc) => loc.toLowerCase().includes(q))
    : LOCATION_SUGGESTIONS;
  return pool.slice(0, limit).map((value) => ({
    value,
    level: locationLevel(value) ?? "Upazila",
  }));
};
